# Reference:
# https://auth0.com/blog/use-docker-to-create-a-node-development-environment/#docker-compose

version: "3.8"
services:
  node_dev_env:
    build: ./server
    container_name: node-docker
    ports:
      - 3000:3000
    volumes:
      - ./server:/home/app
    depends_on: 
      - postgres_db
  react_dev_env:
    build: ./client
    container_name: react-docker
    ports: 
      - 3500:3500
    volumes: 
      - ./client:/home/app
  postgres_db:
    build: ./db
    container_name: postgres-docker
    environment: 
      - POSTGRES_DB=wallet
      - POSTGRES_PASSWORD=db-password
    ports:
      - 5432:5432
    volumes: 
      - ./db/data:/var/lib/postgresql/data
